spring.application.name=greenpass
server.servlet.context-path=/api/v1

# spring.datasource.url=jdbc:mysql://localhost:3307/greenpass_db?characterEncoding=UTF-8&useLegacyDatetimeCode=false
# spring.datasource.username=root
# spring.datasource.password=1234

spring.datasource.url=jdbc:mysql://switchyard.proxy.rlwy.net:28790/railway
spring.datasource.username=root
spring.datasource.password=bKlkjdXvOyXJMYfaLZftivSBQgQnmaQu

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8081